name: Update Filtered Repo

on:
  workflow_dispatch:

  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: mypack
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Download original index.json
        run: |
          curl -s -L "https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.json" -o original_index.json

      - name: Run filter
        run: |
          python filter_extensions.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Chore: Auto Update Extensions"
          branch: mypack
          file_pattern: 'index.json index.min.json'